# # .github/workflows/ci-cd.yml


name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn
          # pip install tensorflow

      - name: Linting
        run: |
          pip install flake8
          flake8 wine_qlty.py

      - name: Run Tests
        run: |
           python -m unittest discover

      - name: Deploy Model
        run: |
          python wine_qlty.py

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./path/to/files ec2-user@100.25.28.126:/path/on/ec2

      - name: Run commands on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@100.25.28.126 "bash /path/on/ec2/deploy_script.sh"

# name: CI/CD Pipeline

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: windows-latest
#     env:
#         FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true 
        
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install numpy pandas scikit-learn 
#           # pip install tensorflow

#       - name: Linting
#         run: |
#           pip install flake8
#           flake8 wine_qlty.py

#       - name: Run Tests
#         run: |
#            python -m unittest discover

#       - name: Deploy Model
#         run: |
#           python wine_qlty.py
