# # .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn

      - name: Linting
        run: |
          pip install flake8
          flake8 wine_qlty.py

      - name: Run Tests
        run: |
          python -m unittest discover

      - name: Build Docker image
        run: |
          docker build -t my-docker-image:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag wine-quality-detector:latest ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove any existing container
            docker stop my-container || true
            docker rm my-container || true
            
            # Pull the latest Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
            
            # Run the Docker container
            docker run -d --name my-container -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest

# name: CI/CD Pipeline

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: windows-latest
#     env:
#         FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true 
        
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install numpy pandas scikit-learn 
#           # pip install tensorflow

#       - name: Linting
#         run: |
#           pip install flake8
#           flake8 wine_qlty.py

#       - name: Run Tests
#         run: |
#            python -m unittest discover

#       - name: Deploy Model
#         run: |
#           python wine_qlty.py
